default: &default
  adapter: mysql2
  host: localhost
  username: <%= ENV['MYSQL_USERNAME'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  pool: 5
  timeout: 5000
  encoding: utf8mb4

development:
  <<: *default
  database: webs

test:
  <<: *default
  database: test_awesomes

production:
  <<: *default
  database: <%= ENV['MYSQL_DATABASE'] %>
  host: <%= ENV['MYSQL_HOST'] %>
  username: <%= ENV['MYSQL_USERNAME'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>

